version: '2'

volumes:
  orderer.example.com:

networks:
  fabric:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    environment:
      - ORDERER_HOST=orderer.example.com
    extra_hosts:
      - "peer0.org1.example.com:$PEER0_ORG1_HOST"
      - "peer0.org2.example.com:$PEER0_ORG2_HOST"
      - "peer0.org3.example.com:$PEER0_ORG3_HOST"
      - "peer1.org1.example.com:$PEER1_ORG1_HOST"
      - "peer1.org2.example.com:$PEER1_ORG2_HOST"
      - "peer1.org3.example.com:$PEER1_ORG3_HOST"
    networks:
      fabric:
        aliases:
          - net
